[package]
name = "prog-lang"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
clap = { version = "4.5.4", features = ["derive"] }
pest = "2.7.9"
pest_derive = "2.7.9"
actix-web = "4"
serde = "1.0.199"
serde-error = "0.1.2"
serde_json = "1.0.116"
actix-cors = "0.7.0"
